--"1ST EX"
USE master;
GO

CREATE DATABASE CONTROL_WORK
ON PRIMARY(
NAME = Arch1,  
FILENAME = 'D:\SalesData\archdat1.mdf',    
FILEGROWTH = 10 MB),(
NAME = Arch2,  
FILENAME = 'C:\SalesData\archdat2.ndf',  
SIZE = 100MB),  
( NAME = Arch3,  
FILENAME = 'D:\SalesData\archdat3.ndf',
FILEGROWTH = 15%)
GO

DROP DATABASE Arch2

--"2ND EX"
--Создание бд
CREATE DATABASE SECOND_EX;
GO
USE SECOND_EX;
GO
--Создаем таблицы
CREATE TABLE PTS(
NOMDOG INT,
KODDET INT,
EDIZM VARCHAR,
DTN DATE NOT NULL CONSTRAINT CK_DTN_LESS_DATA CHECK ("DTN" > '01.05.2004'),
DTK DATE NOT NULL,
STOIM INT CONSTRAINT CK_STOIM_LESS_0 CHECK("STOIM">'0'));
GO
ALTER TABLE PTS ADD CONSTRAINT CK_DTN_LESS_DATA_DTN CHECK ("DTK">"DTN")
CREATE TABLE DOG(
NOMDOG INT,
NAME_PST VARCHAR,
DTDOG DATE NOT NULL,
ADR_PST VARCHAR);
GO
CREATE TABLE PSTS(
NAMEPST VARCHAR,
ADRPST VARCHAR,
INN NUMERIC(10,0),
FIO_RUK VARCHAR(30),)
--связь
ALTER TABLE PTS
ADD FOREIGN KEY (NOMDOG) REFERENCES DOG (NOMDOG)
ON DELETE CASCADE; 
ALTER TABLE PSTS DROP COLUMN ADRPST;
--добавим новые поля
ALTER TABLE PSTS ADD GOROD VARCHAR;
GO
ALTER TABLE PSTS ADD ULICA VARCHAR;
GO
ALTER TABLE PSTS ADD KOD_PSTS INTEGER;
GO
--удалить CONSTRAINT
ALTER TABLE PST DROP CONSTRAINT CK_DTN_LESS_DATA_DTN;
GO
ALTER TABLE PST ADD PLANS INT;
GO
--добавим первиный ключ
ALTER TABLE PST
ADD CONSTRAINT AK_PASSWORD PRIMARY KEY(NOMDOG,KODNET,DTN);
GO
--пишем новое ограничение
ALTER TABLE PST ADD CONSTRAINT CK_DTK_DTN
CHECK ('DTK'-'DTN'<30);
GO