// <auto-generated />
using System;
using Forum.App.DataBase.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Forum.App.Migrations
{
    [DbContext(typeof(ForumDbContext))]
    partial class ForumDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Forum.App.DataBase.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ParentId");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Forum.App.DataBase.Entities.Subforum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Forums");
                });

            modelBuilder.Entity("Forum.App.DataBase.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int?>("SubforumId");

                    b.HasKey("Id");

                    b.HasIndex("SubforumId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Forum.App.DataBase.Entities.Message", b =>
                {
                    b.HasOne("Forum.App.DataBase.Entities.Subject", "Parent")
                        .WithMany("Messages")
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("Forum.App.DataBase.Entities.Subject", b =>
                {
                    b.HasOne("Forum.App.DataBase.Entities.Subforum")
                        .WithMany("Subjects")
                        .HasForeignKey("SubforumId");
                });
#pragma warning restore 612, 618
        }
    }
}
